c0 {
    boolean m0
    boolean m1
    integer m2
    boolean m3
    integer m4 
    f0(a0 : integer, a1 : integer) -> integer {
        while f0(false) {
            print false
            }
        
        print (true)
        return 152
        }
	--! The eror should be thrown
	after this comment
	because this comment
	is well-formed !--
    f1(integer : var1) -> integer {
        boolean l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11
        integer l12
        l4 = true * true
        return f1(true)
        }
    }
c1 extends c0 {
    c0 m0
    c0 m1
    c0 m2
    integer m3
    c0 m4
    c0 m5
    c0 m6
    f0(a0 : c0) -> none {
        c0 l0
        l0.m2 = true
        l0 f1(-l0.m0, 46)
        l0 f1(true, l0 f1(f0(new c0)))
        f1(223)
        
        }
    }
c2 extends c0 {
    c0 m0
    boolean m1
    c0 m2
    c1 m3
    c0 m4
    c1 m5
    c1 m6
    c0 m7
    f0(a0 : boolean, a1 : c1) -> c0 {
        c1 l0, l1
        l1 f1(new c0)
        return l0 f1(false) - f0(new c1 ( l0.m3 ) , l0.m0)
        }
    }
